-- 003: Drugs (ยา) — generic drug names with categories

INSERT INTO drugs (generic_name, drug_category, is_active)
VALUES
  ('cyclophosphamide', 'chemotherapy', true),
  ('ifosfamide', 'chemotherapy', true),
  ('carmustine', 'chemotherapy', true),
  ('busulfan', 'chemotherapy', true),
  ('chlorambucil', 'chemotherapy', true),
  ('melphalan', 'chemotherapy', true),
  ('dacarbazine', 'chemotherapy', true),
  ('cisplatin', 'chemotherapy', true),
  ('carboplatin', 'chemotherapy', true),
  ('oxaliplatin', 'chemotherapy', true),
  ('fluorouracil', 'chemotherapy', true),
  ('capecitabine', 'chemotherapy', true),
  ('methotrexate', 'chemotherapy', true),
  ('cytarabine', 'chemotherapy', true),
  ('gemcitabine', 'chemotherapy', true),
  ('fludarabine phosphate', 'chemotherapy', true),
  ('mercaptopurine', 'chemotherapy', true),
  ('tioguanine', 'chemotherapy', true),
  ('UFT (tegafur-uracil)', 'chemotherapy', true),
  ('doxorubicin hydrochloride', 'chemotherapy', true),
  ('idarubicin hydrochloride', 'chemotherapy', true),
  ('etoposide', 'chemotherapy', true),
  ('irinotecan hydrochloride', 'chemotherapy', true),
  ('topotecan', 'chemotherapy', true),
  ('paclitaxel', 'chemotherapy', true),
  ('docetaxel', 'chemotherapy', true),
  ('vincristine sulfate', 'chemotherapy', true),
  ('vinblastine sulfate', 'chemotherapy', true),
  ('vinorelbine', 'chemotherapy', true),
  ('bleomycin hydrochloride', 'chemotherapy', true),
  ('bleomycin sulfate', 'chemotherapy', true),
  ('dactinomycin', 'chemotherapy', true),
  ('mitomycin', 'chemotherapy', true),
  ('mitoxantrone', 'chemotherapy', true),
  ('tamoxifen', 'hormonal', true),
  ('letrozole', 'hormonal', true),
  ('anastrozole', 'hormonal', true),
  ('bicalutamide', 'hormonal', true),
  ('flutamide', 'hormonal', true),
  ('megestrol acetate', 'hormonal', true),
  ('leuprorelin acetate', 'hormonal', true),
  ('triptorelin', 'hormonal', true),
  ('fulvestrant', 'hormonal', true),
  ('imatinib', 'targeted_therapy', true),
  ('dasatinib', 'targeted_therapy', true),
  ('nilotinib', 'targeted_therapy', true),
  ('trastuzumab', 'targeted_therapy', true),
  ('rituximab', 'targeted_therapy', true),
  ('everolimus', 'targeted_therapy', true),
  ('erlotinib', 'targeted_therapy', true),
  ('gefitinib', 'targeted_therapy', true),
  ('afatinib', 'targeted_therapy', true),
  ('ribociclib', 'targeted_therapy', true),
  ('palbociclib', 'targeted_therapy', true),
  ('tretinoin', 'chemotherapy', true),
  ('arsenic trioxide', 'chemotherapy', true),
  ('filgrastim', 'supportive', true),
  ('lenograstim', 'supportive', true),
  ('mesna', 'supportive', true),
  ('folinic acid', 'supportive', true),
  ('allopurinol', 'supportive', true),
  ('zoledronic acid', 'supportive', true),
  ('prednisolone', 'supportive', true),
  ('hydrocortisone', 'supportive', true),
  ('hydroxycarbamide', 'supportive', true),
  ('ketoconazole', 'supportive', true),
  ('BCG vaccine', 'immunotherapy', true),
  ('ATG', 'immunotherapy', true),
  ('asparaginase', 'chemotherapy', true),
  ('abiraterone', 'targeted', true),
  ('acyclovir', 'supportive', true),
  ('alectinib', 'targeted', true),
  ('aprepitant', 'supportive', true),
  ('atezolizumab', 'immunotherapy', true),
  ('azacitidine', 'chemotherapy', true),
  ('bevacizumab', 'targeted', true),
  ('bortezomib', 'targeted', true),
  ('cetuximab', 'targeted', true),
  ('crizotinib', 'targeted', true),
  ('daunorubicin', 'chemotherapy', true),
  ('dexamethasone', 'supportive', true),
  ('enzalutamide', 'targeted', true),
  ('goserelin', 'hormone', true),
  ('lenalidomide', 'targeted', true),
  ('methylprednisolone', 'supportive', true),
  ('nivolumab', 'immunotherapy', true),
  ('ondansetron', 'supportive', true),
  ('osimertinib', 'targeted', true),
  ('pazopanib', 'targeted', true),
  ('pegfilgrastim', 'supportive', true),
  ('pembrolizumab', 'immunotherapy', true),
  ('pemetrexed', 'chemotherapy', true),
  ('pertuzumab', 'targeted', true),
  ('regorafenib', 'targeted', true),
  ('sodium bicarbonate', 'supportive', true),
  ('sorafenib', 'targeted', true),
  ('sunitinib', 'targeted', true),
  ('thalidomide', 'targeted', true)
ON CONFLICT (generic_name) DO NOTHING;
