-- 006: Regimens (สูตรยา) — chemotherapy regimen definitions

INSERT INTO regimens (regimen_code, regimen_name, description, cycle_days, max_cycles, regimen_type, is_active)
VALUES
  ('AC', 'AC (Doxorubicin + Cyclophosphamide)', 'Doxorubicin 60 mg/m2 IV Day 1 + Cyclophosphamide 600 mg/m2 IV Day 1', 21, 4, 'chemotherapy', true),
  ('TC', 'TC (Docetaxel + Cyclophosphamide)', 'Docetaxel 75 mg/m2 IV Day 1 + Cyclophosphamide 600 mg/m2 IV Day 1', 21, 4, 'chemotherapy', true),
  ('TAC', 'TAC (Docetaxel + Doxorubicin + Cyclophosphamide)', 'Docetaxel 75 mg/m2 + Doxorubicin 50 mg/m2 + Cyclophosphamide 500 mg/m2 Day 1', 21, 6, 'chemotherapy', true),
  ('FAC', 'FAC (Fluorouracil + Doxorubicin + Cyclophosphamide)', 'Fluorouracil 500 mg/m2 + Doxorubicin 50 mg/m2 + Cyclophosphamide 500 mg/m2', 21, 6, 'chemotherapy', true),
  ('FEC', 'FEC (Fluorouracil + Epirubicin + Cyclophosphamide)', 'Fluorouracil 500 mg/m2 + Epirubicin 100 mg/m2 + Cyclophosphamide 500 mg/m2', 21, 6, 'chemotherapy', true),
  ('CMF', 'CMF (Cyclophosphamide + Methotrexate + Fluorouracil)', 'Cyclophosphamide 100 mg/m2 PO D1-14 + MTX 40 mg/m2 IV D1,8 + 5-FU 600 mg/m2 IV D1,8', 28, 6, 'chemotherapy', true),
  ('AC-T', 'AC followed by Paclitaxel', 'AC x 4 cycles then Paclitaxel 80 mg/m2 weekly x 12 or 175 mg/m2 q3w x 4', 21, 8, 'chemotherapy', true),
  ('RIBO-LET', 'Ribociclib + Letrozole', 'Ribociclib 600 mg PO daily D1-21 + Letrozole 2.5 mg PO daily; 28-day cycle', 28, NULL, 'targeted', true),
  ('RIBO-FUL', 'Ribociclib + Fulvestrant', 'Ribociclib 600 mg PO daily D1-21 + Fulvestrant 500 mg IM D1,15 (C1), D1; 28-day cycle', 28, NULL, 'targeted', true),
  ('PALBO-LET', 'Palbociclib + Letrozole', 'Palbociclib 125 mg PO daily D1-21 + Letrozole 2.5 mg PO daily; 28-day cycle', 28, NULL, 'targeted', true),
  ('PALBO-FUL', 'Palbociclib + Fulvestrant', 'Palbociclib 125 mg PO daily D1-21 + Fulvestrant 500 mg IM; 28-day cycle', 28, NULL, 'targeted', true),
  ('PACLI-TRAS', 'Paclitaxel + Trastuzumab', 'Paclitaxel 80 mg/m2 weekly + Trastuzumab q3w', 21, NULL, 'chemotherapy', true),
  ('CAPE-MONO', 'Capecitabine monotherapy', 'Capecitabine 1000-1250 mg/m2 PO BID D1-14', 21, NULL, 'chemotherapy', true),
  ('FOLFOX4', 'FOLFOX4 (5-FU + Leucovorin + Oxaliplatin)', 'Oxaliplatin 85 mg/m2 D1 + LV 200 mg/m2 D1,2 + 5-FU bolus 400 mg/m2 D1,2 + 5-FU CI 600 mg/m2 D1,2', 14, 12, 'chemotherapy', true),
  ('mFOLFOX6', 'mFOLFOX6 (modified FOLFOX6)', 'Oxaliplatin 85 mg/m2 D1 + LV 400 mg/m2 D1 + 5-FU bolus 400 mg/m2 D1 + 5-FU CI 2400 mg/m2 46h', 14, 12, 'chemotherapy', true),
  ('FOLFIRI', 'FOLFIRI (5-FU + Leucovorin + Irinotecan)', 'Irinotecan 180 mg/m2 D1 + LV 400 mg/m2 D1 + 5-FU bolus 400 mg/m2 D1 + 5-FU CI 2400 mg/m2 46h', 14, NULL, 'chemotherapy', true),
  ('XELOX', 'XELOX/CAPOX (Capecitabine + Oxaliplatin)', 'Oxaliplatin 130 mg/m2 IV D1 + Capecitabine 1000 mg/m2 PO BID D1-14', 21, 8, 'chemotherapy', true),
  ('5FU-LV', '5-FU/LV (Fluorouracil + Leucovorin)', 'Fluorouracil + Leucovorin various schedules', 14, NULL, 'chemotherapy', true),
  ('HIPEC-MMC', 'HIPEC with Mitomycin C', 'Mitomycin C intraperitoneal during HIPEC procedure', NULL, 1, 'chemotherapy', true),
  ('CIS-ETO', 'EP (Cisplatin + Etoposide)', 'Cisplatin 75-80 mg/m2 D1 + Etoposide 100 mg/m2 D1-3', 21, 4, 'chemotherapy', true),
  ('CARBO-PACLI', 'Carboplatin + Paclitaxel', 'Carboplatin AUC 5-6 D1 + Paclitaxel 175-200 mg/m2 D1', 21, 4, 'chemotherapy', true),
  ('CARBO-ETO', 'Carboplatin + Etoposide', 'Carboplatin AUC 5 D1 + Etoposide 100 mg/m2 D1-3', 21, 4, 'chemotherapy', true),
  ('GEM-CIS', 'Gemcitabine + Cisplatin', 'Gemcitabine 1000-1250 mg/m2 D1,8 + Cisplatin 75 mg/m2 D1', 21, 4, 'chemotherapy', true),
  ('GEM-CARBO', 'Gemcitabine + Carboplatin', 'Gemcitabine 1000 mg/m2 D1,8 + Carboplatin AUC 5 D1', 21, 4, 'chemotherapy', true),
  ('DOCE-MONO', 'Docetaxel monotherapy', 'Docetaxel 75 mg/m2 IV Day 1', 21, NULL, 'chemotherapy', true),
  ('CIS-RT', 'Cisplatin concurrent with radiation', 'Cisplatin 40 mg/m2 weekly during radiation or 100 mg/m2 q3w', 7, NULL, 'chemoradiation', true),
  ('TPF', 'TPF (Docetaxel + Cisplatin + Fluorouracil)', 'Docetaxel 75 mg/m2 D1 + Cisplatin 75 mg/m2 D1 + 5-FU 750 mg/m2 D1-5', 21, 3, 'chemotherapy', true),
  ('CIS-5FU', 'Cisplatin + 5-FU', 'Cisplatin 100 mg/m2 D1 + Fluorouracil 1000 mg/m2 D1-4 CI', 21, NULL, 'chemotherapy', true),
  ('XELOX-GAST', 'XELOX for Gastric Cancer', 'Oxaliplatin 130 mg/m2 D1 + Capecitabine 1000 mg/m2 BID D1-14', 21, 8, 'chemotherapy', true),
  ('ECF', 'ECF (Epirubicin + Cisplatin + 5-FU)', 'Epirubicin 50 mg/m2 D1 + Cisplatin 60 mg/m2 D1 + 5-FU 200 mg/m2 daily CI', 21, 6, 'chemotherapy', true),
  ('CHOP', 'CHOP (Cyclophosphamide + Doxorubicin + Vincristine + Prednisolone)', 'CTX 750 mg/m2 D1 + Doxo 50 mg/m2 D1 + VCR 1.4 mg/m2 D1 + Pred 100 mg D1-5', 21, 6, 'chemotherapy', true),
  ('R-CHOP', 'R-CHOP (Rituximab + CHOP)', 'Rituximab 375 mg/m2 D1 + CHOP', 21, 6, 'chemo_immuno', true),
  ('CVP', 'CVP (Cyclophosphamide + Vincristine + Prednisolone)', 'CTX 750 mg/m2 D1 + VCR 1.4 mg/m2 D1 + Pred 40 mg/m2 D1-5', 21, 6, 'chemotherapy', true),
  ('R-CVP', 'R-CVP (Rituximab + CVP)', 'Rituximab 375 mg/m2 D1 + CVP', 21, 6, 'chemo_immuno', true),
  ('ABVD', 'ABVD (Doxorubicin + Bleomycin + Vinblastine + Dacarbazine)', 'Doxo 25 mg/m2 D1,15 + Bleo 10 U/m2 D1,15 + VBL 6 mg/m2 D1,15 + DTIC 375 mg/m2 D1,15', 28, 6, 'chemotherapy', true),
  ('HYPER-CVAD', 'Hyper-CVAD', 'Cyclophosphamide + Vincristine + Doxorubicin + Dexamethasone alternating with high-dose MTX + Ara-C', 21, 8, 'chemotherapy', true),
  ('7-PLUS-3', '7+3 (Cytarabine + Daunorubicin/Idarubicin)', 'Cytarabine 100-200 mg/m2 CI D1-7 + Anthracycline D1-3', 28, NULL, 'chemotherapy', true),
  ('ATRA', 'ATRA (All-trans retinoic acid)', 'Tretinoin 45 mg/m2/day PO until complete remission', NULL, NULL, 'chemotherapy', true),
  ('IMATINIB-CML', 'Imatinib for CML', 'Imatinib 400-600 mg PO daily, continuous', NULL, NULL, 'targeted', true),
  ('BEP', 'BEP (Bleomycin + Etoposide + Cisplatin)', 'Bleomycin 30 U D1,8,15 + Etoposide 100 mg/m2 D1-5 + Cisplatin 20 mg/m2 D1-5', 21, 3, 'chemotherapy', true),
  ('VDC-IE', 'VDC/IE alternating', 'VDC (Vincristine + Doxorubicin + Cyclophosphamide) alt with IE (Ifosfamide + Etoposide)', 21, NULL, 'chemotherapy', true),
  ('DOXO-MONO', 'Doxorubicin monotherapy', 'Doxorubicin 75 mg/m2 IV Day 1', 21, NULL, 'chemotherapy', true),
  ('CARBO-PACLI-GYN', 'Carboplatin + Paclitaxel (Gynecologic)', 'Carboplatin AUC 5-6 D1 + Paclitaxel 175 mg/m2 D1', 21, 6, 'chemotherapy', true),
  ('DOCE-PRED', 'Docetaxel + Prednisolone', 'Docetaxel 75 mg/m2 q3w + Prednisolone 5 mg BID daily', 21, 10, 'chemotherapy', true),
  ('LHRH-AGONIST', 'LHRH Agonist therapy', 'Leuprorelin or Triptorelin injection q3m or q6m', 84, NULL, 'hormonal', true)
ON CONFLICT (regimen_code) DO NOTHING;
